# Generated by Django 5.2.4 on 2025-07-29 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0002_alter_destination_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='desc',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='destination',
            name='name',
            field=models.TextField(max_length=100),
        ),
    ]
