# Generated by Django 5.2.4 on 2025-07-30 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0003_alter_destination_desc_alter_destination_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='t_destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('price', models.IntegerField()),
                ('desc', models.TextField(max_length=200)),
                ('img', models.ImageField(upload_to='pics')),
            ],
        ),
    ]
